---

name: Build

on:
  push:
    paths:
      - cv.tex
      - developercv.cls
  pull_request:
    paths:
      - cv.tex
      - developercv.cls
  workflow_dispatch:

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo
        uses: actions/checkout@v2
      - name: Create PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
      - name: Push to GH-Pages branch
        uses: EndBug/add-and-commit@v7
        with:
          add: cv.pdf
          message: Updating CV
          push: true
